<a href="https://colab.research.google.com/github/Pratiksha0409/sujan/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Simple python program using numpy 

In [1]:
import numpy as np
x=np.array([1,2,3])
y=np.array([1,2,4])
x+y
a=np.add(x,y)
m=np.multiply(x,y)
print(a,m)

[2 4 7] [ 1  4 12]


Using tensorflow 1.0

In [4]:
import tensorflow as tf
x=tf.constant([1,2,3])
y=tf.constant([1,2,4])
a=tf.add(x,y)
print(a)

tf.Tensor([2 4 7], shape=(3,), dtype=int32)


In [5]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [6]:
x=tf.constant([1,2,3])
y=tf.constant([1,2,4])
a=tf.add(x,y)
print(a)

tf.Tensor([2 4 7], shape=(3,), dtype=int32)
